// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "Neogennium Technologies", "neogennium technologies artificial intelligence and technology for markets science engineering home nbsp solutions about us contact english brazilian portuguese papers ", "Artificial intelligence and technology for makets  science and engineering ");
   this[database_length++] = new SearchPage("solutions.html", "Neogennium - Solutions", "neogennium solutions carbon dioxide assessment and calculation for highway construction maintenance activities traffic of vehicles pavement management optimized by genetic algorithms stock market commodities artificial intelligence based modeling that works optimum buy or sell recommendation trailing stop read more state the art design with traditional mechanistic methodologies finite element analysis optimization models work any kind asset prices available in metastock format advertising selectionallocate purchases within budget among media tv radio newspaper internet which have various price breaks nbsp maximize people reached assignment tasks assign workers to maximizing overall efficiency exemple crew allocation airliners use aircraft fleet manufacturing departments plan mix products profit while all customers suppliers contracts are fulfilled line production runs condition portfolio balancefind optimal investments your given current risk return needs space navigation amount direction each rocket thrust reach destination using least fuel considering gravitational effect transportation shippingminimize costs shipping goods from plants warehouses not exceeding supply plant meeting demand metropolitan area route planningthe shortest visit large number locations making sure some visited before others additional requirements decision support oil industry prediction neural networks distresses detection unique methodology on capable detect patterns pictures software development big data intelligencedata mining knowledge discovering optimizations performance road pavements iri international roughness index cracked rutting deflections macrotexture home papers about us contact english brazilian portuguese ", "Artificial intelligence and traditional solutions for markets  science and engineering ");
   this[database_length++] = new SearchPage("papers.html", "Neogennium - Solutions", "neogennium solutions salini´s scientific papers and thesis year of publication nbsp utilização de borracha reciclada pneus em misturas asfálticas avaliação da capacidade estrutural dos pavimentos partir dados deflectométricos proposição metodologia original in english study recycled tyre rubber asphalt concrete mixturestradução para português estudo sobre incorporação concreto asfáltico sc crumb tire mixtures salini method paper free software the road map to apply evolutionary intelligence pavement modelling definition situ instrumentation for data collection develop performance model artificial xxi century paradigm design intellipave considering aside failure criteria unknown variables based models uma abordagem baseada inteligência modelagem asfálticos phd asset management rural urban development suggested moldova application optimization greenhouse gas assessment compensation on brazilian low volume roads with carbonroad santa rosa lima case impact image resolution distress detection using picucha methodology neural networks rolling resistance estimating new implications changing maximum legal truck load service life area scan cameras dark images hybrid human approach home about us contact portuguese ", "Artificial intelligence and traditional solutions for markets  science and engineering ");
   this[database_length++] = new SearchPage("about-us.html", "Neogennium - About us", "neogennium about us technologiesneogennium has offered technological solutions and engineering services for customers since the most important have been road management authorities as well infrastructure sector contractors consultants in brazil europe our software achieved widespread recognition excellent practice innovative usefulness of operation news quot million dollar transportation project brazilseven consortia registered feasibility studies on bridge linking santa catarina island florianopolis more know howour competitiveness is based continuous development knowledge business creativity to combine latest technology especially artificial intelligence tools customer specific visit page information operating modelneogennium aims be widely networked leading service provider worldwide active following global advancements innovation developing home papers nbsp contact english brazilian portuguese ", "About us ");
   this[database_length++] = new SearchPage("contact.html", "Neogennium - Contact", "neogennium contact brazil sweden usa home solutions papers about nbsp us english brazilian portuguese ", "Contact us");
   this[database_length++] = new SearchPage("br/index.html", "Neogennium Technologies", "neogennium technologies inteligência artificial tecnologia para mercado financeiro ciências engenharia home nbsp soluções quem somos contato english brazilian portuguese solu es papers ", "Inteligência artificial e tecnologia para o mercado financeiro  ciências e engenharia ");
   this[database_length++] = new SearchPage("br/solucoes.html", "Neogennium - Soluções", "neogennium soluções determinaçao das emissões decarbono resultante da construção manutenção de estradas tráfego veículos gerência pavimentos otimizada com algoritmos genéticos bolsa valores commodities modelos baseados em inteligência artificial que funcionam identificação dos pontos ideais compra venda otimização stop móvel ler mais projeto wempregando metodologias tradicionais abordagem mecanística modelagem elementos finitos análise técnicas os qualquer tipo ativo financeiro ou não possua preços disponíveis formato metastock propaganda merchandesignaquisição espaços dentro limitações financeiras considerando diversas mídias tv rádio jornais internet possuem alcance diferenciados maximize quantidade consumidores alcançados equipes atribuir as tarefas aos colaboradores maximizando eficiênciaexemplo alocação tripulação aeronaves uso frota aviões produção verbas entre departamentos planejamento do mix produtos enquanto todos clientes contratos fornecedores são atendidos linha opera condições balanceamento portfolio ideal investimentos para maximizar rentabilidade acordo perfil risco retorno navegação espacial direção cada foguete propulsor chegar determinado destino utilizando menor possível combustível efeito gravitacional transporte remessasminimize custo envio plantas centros distribuição ultrapassa capacidade planta atende demanda cidade atendida rotasidentificação rota curta visitar diversos locais certos destinos visitados prioridade outros requisitos suporte tomada decisão indústria petróleo outras predição resultados redes neurais detecção defeitos metodologia baseada capaz detectar patterns imagens leia performance rodoviários iri international roughness index Área trincada trilha roda deflexões macrotextura muito home nbsp quem somos contato english brazilian portuguese solu es papers ", "Soluções para os mercados financeiros  engenharia e pesquisas científicas ");
   this[database_length++] = new SearchPage("br/quem-somos.html", "Neogennium - Quem somos", "neogennium quem somos technologiesa tem oferecido soluções de tecnologia serviços engenharia desde os principais clientes são departamentos estradas empreiteiros da infra estrutura empresas consultiva no brasil na europa nossos software reconhecidos como inovadores elevado padrão excelência notícias apresenta proposta em competição internacional para ligação ilha continente florianópolisos sete projetos estudos preliminares transporte massa resolver congestionamentos diários nas pontes que ligam parte continental florianópolis foram conhecidos nesta quarta feira leia mais nosso know hownossa competitividade baseada contínuo desenvolvimento tecnológico combinado as avançadas tecnologias técnicas inteligência artificial desenvolver customizadas visite nossa página maiores informações modelo operaçõesa possui uma grande rede contatos perceiros nível mundial operação acompanhar ativamente avanços globais inovação home solu es papers nbsp contato english brazilian portuguese ", "Quem somos   ");
   this[database_length++] = new SearchPage("br/contato.html", "Neogennium - Contato", "neogennium contato brazil sweden usa home nbsp soluções quem somos english brazilian portuguese solu es papers ", "Entre em contato ");
   this[database_length++] = new SearchPage("br/modelos-para-o-mercado.html", "Neogennium - Modelos e Trading Systems baseados em inteligência artificial", "neogennium modelos trading systems baseados em inteligência artificial mercado de ações commodities mais que funcionam nbsp identificação dos pontos ótimos compra venda sem stress nem correria otimizados para gerar poucas operações por ano stop móvel otimizado proporcionar excelente controle risco evitar disparos indesejados adequados qualquer tipo ativo financeiro ou não com preços disponíveis formato metastock resilientes vida típica entre seis meses três perfis investidores adequado ativos operam apenas na ponta compradora desejam aproveitar as osciações do reduzir preço médio aquisição investimento potencializar os lucros substituição buy and hold protegendo posição descoberto avançados grande experiência no descoberta ambas direções dinâmicos buscam lucro condição enquanto protegem móveis home solu es papers quem somos contato soluções english brazilian portuguese ", "Modelos de predição de preço para o mercado financeiro  ações  commodities      ");
   this[database_length++] = new SearchPage("br/deteccao-defeitos-pavimentos.html", "Neogennium", "neogennium picucha uma nova metodologia para inventário de defeitos pavimentos ruas rodovias levantamento da condição funcional superfície dos um fatores mais importantes gerenciamento bem como elaboração projetos restauração os levantamentos efetuados através processos manuais comuns décadas atrás não sáo viáveis devido aos elevados custos riscos avaliadores nas com volumes tráfego foram desenvolvidos diversos equipamentos fotografar ou efetuar em identificação mas enquanto estes quipamentos evoluíram ao longo anos software necessário análise dados detecção permanece grande desafio poucos softwares disponíveis geralmente são capazes detectar apenas as trincas acurácia muito inferior necessária desenvolveu baseada inteligência artificial técnicas visão computacional esta chamada capaz identificar buracos remendos pintura sinalização juntas dispositivos drenagem diferentes tipos coloração texturas variáveis incluindo seções mistas asfalto concreto cimento portland qualquer combinação sombras sólidas complexas até mesmo objetos sobre pavimento entre outros totalmente operacional foi desenvolvimento forma onde engenheiro tem oportunidade interagir sistema tomar decisões críticas proporcionando compatível imagens ortogonais quot downward facing registradas equipamento marca resolução tamanho imagem lcms automática home nbsp soluções quem somos contato english brazilian portuguese solu es papers ", "Identificação automática de defeitos de pavimentos  trincas  buracos      ");
   this[database_length++] = new SearchPage("pavement-distresses-detection.html", "Neogennium - Models and Trading Systems with Artificial Intelligence", "neogennium models and trading systems with artificial intelligence picucha new methodology for pavement distresses characteristics assessment the surface condition is one of most important information proper management as well rehabilitation design handmade assessments common decades ago are no longer viable many reasons including high costs risks staff on current trafficked highways number hardware devices were developed to take technical pictures or perform scanning survey but while advanced from steadily software required automatic identification remains challenge few available process picture data usually capable deal just cracks frequently an insufficient accuracy hybrid based computer vision techniques it called detect potholes patches painted signs joints drainage different types pavements textures colors mixed sections asphalt portland cement concrete any combination two more them solid complex shadows even objects dropped over among others fully operational already has been built in way where human expert engineer will have opportunity interact make some key decisions providing unmatchable up compatible orthogonal quot downward facing taken equipment brand at resolution size lcms detectionwith home solutions papers about nbsp us contact english brazilian portuguese ", "Detection of  road  pavement distresses  cracks  potholes       with artificial intelligence techniques ");
   this[database_length++] = new SearchPage("models-for-markets.html", "Neogennium - Models and Trading Systems with Artificial Intelligence", "neogennium models and trading systems with artificial intelligence stock market commodities more based modeling that works nbsp identification of the optimum buying or selling points optimized to generate few operations per year trailing stops keep good risk control reducing unwanted suitable for any kind asset prices available in metastock file format resilient typical life span between six twelve months three different investor profiles buy protective stop active only investors want take advantage movements reduce investment acquisition average price improve profits instead follow hold strategy protecting position short sell without advanced dynamic seeking profit condition while keeping both directions home solutions papers about us contact english brazilian portuguese ", "Modeling for markets based on artificial intelligence techniques  stock  commodities      ");
   this[database_length++] = new SearchPage("404.html", "Error 404 - Page not found", "error page not found ", "Artificial intelligence for markets  science and engineering    Stock market  resilient models that work  Buy and sell recomendations  Optimized trailing stop   Engineering  carbon dioxide assessment for highways contruction and maintenance  and for the traffic of vehicles  Pavement management optimized by artificial intelligence  Pavement design under mechanistic methodologies with finite element modeling ");
   this[database_length++] = new SearchPage("403.html", "Error 403 - Page not found", "error page not found forbidden ", "Error 403");
   this[database_length++] = new SearchPage("formigo_pix.html", "Doação via PIX para o Canal Formigo Atômico no Youtube", "doação via pix para canal formigo atômico no youtube de qualquer valor atômicodonate to channel chave aleatória b1282248 a88a a74 a3ac a1b4f8f696em nome neogennium paypaldonate with paypal pixdonate brazil ", "Artificial intelligence for markets  science and engineering    Stock market  resilient models that work  Buy and sell recomendations  Optimized trailing stop   Engineering  carbon dioxide assessment for highways contruction and maintenance  and for the traffic of vehicles  Pavement management optimized by artificial intelligence  Pavement design under mechanistic methodologies with finite element modeling ");
   this[database_length++] = new SearchPage("googledeveloper/minimatraffic_privacy_policy.html", "MinimaTRAFFIC Privacy Police", "minimatraffic privacy police policeminimatraffic does not monitor collect store or transmit any kind of user device information ", "Artificial intelligence for markets  science and engineering    Stock market  resilient models that work  Buy and sell recomendations  Optimized trailing stop   Engineering  carbon dioxide assessment for highways contruction and maintenance  and for the traffic of vehicles  Pavement management optimized by artificial intelligence  Pavement design under mechanistic methodologies with finite element modeling ");
   return this;
}
